// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MIPMAPDATA_SC_TEXTURE_SCTX_H_
#define FLATBUFFERS_GENERATED_MIPMAPDATA_SC_TEXTURE_SCTX_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace sc {
namespace texture {
namespace SCTX {

struct MipMap;
struct MipMapBuilder;

struct MipMap FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MipMapBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_WIDTH = 4,
    VT_HEIGHT = 6,
    VT_OFFSET = 8,
    VT_HASH = 10
  };
  uint16_t width() const {
    return GetField<uint16_t>(VT_WIDTH, 0);
  }
  uint16_t height() const {
    return GetField<uint16_t>(VT_HEIGHT, 0);
  }
  uint32_t offset() const {
    return GetField<uint32_t>(VT_OFFSET, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *hash() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_HASH);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint16_t>(verifier, VT_WIDTH, 2) &&
           VerifyField<uint16_t>(verifier, VT_HEIGHT, 2) &&
           VerifyField<uint32_t>(verifier, VT_OFFSET, 4) &&
           VerifyOffset(verifier, VT_HASH) &&
           verifier.VerifyVector(hash()) &&
           verifier.EndTable();
  }
};

struct MipMapBuilder {
  typedef MipMap Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_width(uint16_t width) {
    fbb_.AddElement<uint16_t>(MipMap::VT_WIDTH, width, 0);
  }
  void add_height(uint16_t height) {
    fbb_.AddElement<uint16_t>(MipMap::VT_HEIGHT, height, 0);
  }
  void add_offset(uint32_t offset) {
    fbb_.AddElement<uint32_t>(MipMap::VT_OFFSET, offset, 0);
  }
  void add_hash(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash) {
    fbb_.AddOffset(MipMap::VT_HASH, hash);
  }
  explicit MipMapBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MipMap> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MipMap>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MipMap> CreateMipMap(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t width = 0,
    uint16_t height = 0,
    uint32_t offset = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> hash = 0) {
  MipMapBuilder builder_(_fbb);
  builder_.add_hash(hash);
  builder_.add_offset(offset);
  builder_.add_height(height);
  builder_.add_width(width);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<MipMap> CreateMipMapDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint16_t width = 0,
    uint16_t height = 0,
    uint32_t offset = 0,
    const std::vector<uint8_t> *hash = nullptr) {
  auto hash__ = hash ? _fbb.CreateVector<uint8_t>(*hash) : 0;
  return sc::texture::SCTX::CreateMipMap(
      _fbb,
      width,
      height,
      offset,
      hash__);
}

inline const sc::texture::SCTX::MipMap *GetMipMap(const void *buf) {
  return ::flatbuffers::GetRoot<sc::texture::SCTX::MipMap>(buf);
}

inline const sc::texture::SCTX::MipMap *GetSizePrefixedMipMap(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<sc::texture::SCTX::MipMap>(buf);
}

inline bool VerifyMipMapBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<sc::texture::SCTX::MipMap>(nullptr);
}

inline bool VerifySizePrefixedMipMapBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<sc::texture::SCTX::MipMap>(nullptr);
}

inline void FinishMipMapBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sc::texture::SCTX::MipMap> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedMipMapBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sc::texture::SCTX::MipMap> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace SCTX
}  // namespace texture
}  // namespace sc

#endif  // FLATBUFFERS_GENERATED_MIPMAPDATA_SC_TEXTURE_SCTX_H_
