// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_TEXTUREDATA_SC_TEXTURE_SCTX_H_
#define FLATBUFFERS_GENERATED_TEXTUREDATA_SC_TEXTURE_SCTX_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 25 &&
              FLATBUFFERS_VERSION_MINOR == 1 &&
              FLATBUFFERS_VERSION_REVISION == 21,
             "Non-compatible flatbuffers version included");

namespace sc {
namespace texture {
namespace SCTX {

struct StreamingTextureDescriptor;
struct StreamingTextureDescriptorBuilder;

struct TextureVariants;
struct TextureVariantsBuilder;

struct TextureData;
struct TextureDataBuilder;

enum TextureFlags : uint32_t {
  TextureFlags_use_compression = 1,
  TextureFlags_unknown_flag2 = 2,
  TextureFlags_unknown_flag3 = 4,
  TextureFlags_use_padding = 8,
  TextureFlags_NONE = 0,
  TextureFlags_ANY = 15
};

inline const TextureFlags (&EnumValuesTextureFlags())[4] {
  static const TextureFlags values[] = {
    TextureFlags_use_compression,
    TextureFlags_unknown_flag2,
    TextureFlags_unknown_flag3,
    TextureFlags_use_padding
  };
  return values;
}

inline const char * const *EnumNamesTextureFlags() {
  static const char * const names[9] = {
    "use_compression",
    "unknown_flag2",
    "",
    "unknown_flag3",
    "",
    "",
    "",
    "use_padding",
    nullptr
  };
  return names;
}

inline const char *EnumNameTextureFlags(TextureFlags e) {
  if (::flatbuffers::IsOutRange(e, TextureFlags_use_compression, TextureFlags_use_padding)) return "";
  const size_t index = static_cast<size_t>(e) - static_cast<size_t>(TextureFlags_use_compression);
  return EnumNamesTextureFlags()[index];
}

struct StreamingTextureDescriptor FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StreamingTextureDescriptorBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PIXEL_TYPE = 4,
    VT_WIDTH = 6,
    VT_HEIGHT = 8,
    VT_DATA = 10
  };
  uint32_t pixel_type() const {
    return GetField<uint32_t>(VT_PIXEL_TYPE, 0);
  }
  uint16_t width() const {
    return GetField<uint16_t>(VT_WIDTH, 0);
  }
  uint16_t height() const {
    return GetField<uint16_t>(VT_HEIGHT, 0);
  }
  const ::flatbuffers::Vector<uint8_t> *data() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_DATA);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<uint32_t>(verifier, VT_PIXEL_TYPE, 4) &&
           VerifyField<uint16_t>(verifier, VT_WIDTH, 2) &&
           VerifyField<uint16_t>(verifier, VT_HEIGHT, 2) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.EndTable();
  }
};

struct StreamingTextureDescriptorBuilder {
  typedef StreamingTextureDescriptor Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_pixel_type(uint32_t pixel_type) {
    fbb_.AddElement<uint32_t>(StreamingTextureDescriptor::VT_PIXEL_TYPE, pixel_type, 0);
  }
  void add_width(uint16_t width) {
    fbb_.AddElement<uint16_t>(StreamingTextureDescriptor::VT_WIDTH, width, 0);
  }
  void add_height(uint16_t height) {
    fbb_.AddElement<uint16_t>(StreamingTextureDescriptor::VT_HEIGHT, height, 0);
  }
  void add_data(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data) {
    fbb_.AddOffset(StreamingTextureDescriptor::VT_DATA, data);
  }
  explicit StreamingTextureDescriptorBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StreamingTextureDescriptor> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StreamingTextureDescriptor>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StreamingTextureDescriptor> CreateStreamingTextureDescriptor(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t pixel_type = 0,
    uint16_t width = 0,
    uint16_t height = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> data = 0) {
  StreamingTextureDescriptorBuilder builder_(_fbb);
  builder_.add_data(data);
  builder_.add_pixel_type(pixel_type);
  builder_.add_height(height);
  builder_.add_width(width);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<StreamingTextureDescriptor> CreateStreamingTextureDescriptorDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    uint32_t pixel_type = 0,
    uint16_t width = 0,
    uint16_t height = 0,
    const std::vector<uint8_t> *data = nullptr) {
  auto data__ = data ? _fbb.CreateVector<uint8_t>(*data) : 0;
  return sc::texture::SCTX::CreateStreamingTextureDescriptor(
      _fbb,
      pixel_type,
      width,
      height,
      data__);
}

struct TextureVariants FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TextureVariantsBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_STREAMING_ID = 4,
    VT_STREAMING_TEXTURES = 6
  };
  const ::flatbuffers::Vector<uint32_t> *streaming_id() const {
    return GetPointer<const ::flatbuffers::Vector<uint32_t> *>(VT_STREAMING_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<sc::texture::SCTX::StreamingTextureDescriptor>> *streaming_textures() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<sc::texture::SCTX::StreamingTextureDescriptor>> *>(VT_STREAMING_TEXTURES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_STREAMING_ID) &&
           verifier.VerifyVector(streaming_id()) &&
           VerifyOffset(verifier, VT_STREAMING_TEXTURES) &&
           verifier.VerifyVector(streaming_textures()) &&
           verifier.VerifyVectorOfTables(streaming_textures()) &&
           verifier.EndTable();
  }
};

struct TextureVariantsBuilder {
  typedef TextureVariants Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_streaming_id(::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> streaming_id) {
    fbb_.AddOffset(TextureVariants::VT_STREAMING_ID, streaming_id);
  }
  void add_streaming_textures(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<sc::texture::SCTX::StreamingTextureDescriptor>>> streaming_textures) {
    fbb_.AddOffset(TextureVariants::VT_STREAMING_TEXTURES, streaming_textures);
  }
  explicit TextureVariantsBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TextureVariants> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TextureVariants>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TextureVariants> CreateTextureVariants(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint32_t>> streaming_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<sc::texture::SCTX::StreamingTextureDescriptor>>> streaming_textures = 0) {
  TextureVariantsBuilder builder_(_fbb);
  builder_.add_streaming_textures(streaming_textures);
  builder_.add_streaming_id(streaming_id);
  return builder_.Finish();
}

inline ::flatbuffers::Offset<TextureVariants> CreateTextureVariantsDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<uint32_t> *streaming_id = nullptr,
    const std::vector<::flatbuffers::Offset<sc::texture::SCTX::StreamingTextureDescriptor>> *streaming_textures = nullptr) {
  auto streaming_id__ = streaming_id ? _fbb.CreateVector<uint32_t>(*streaming_id) : 0;
  auto streaming_textures__ = streaming_textures ? _fbb.CreateVector<::flatbuffers::Offset<sc::texture::SCTX::StreamingTextureDescriptor>>(*streaming_textures) : 0;
  return sc::texture::SCTX::CreateTextureVariants(
      _fbb,
      streaming_id__,
      streaming_textures__);
}

struct TextureData FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TextureDataBuilder Builder;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNK1 = 4,
    VT_PIXEL_TYPE = 6,
    VT_WIDTH = 8,
    VT_HEIGHT = 10,
    VT_LEVELS_COUNT = 12,
    VT_UNK3 = 14,
    VT_FLAGS = 16,
    VT_TEXTURE_LENGTH = 18,
    VT_UNK5 = 20,
    VT_UNK6 = 22,
    VT_VARIANTS = 24
  };
  int32_t unk1() const {
    return GetField<int32_t>(VT_UNK1, 0);
  }
  uint32_t pixel_type() const {
    return GetField<uint32_t>(VT_PIXEL_TYPE, 0);
  }
  uint16_t width() const {
    return GetField<uint16_t>(VT_WIDTH, 0);
  }
  uint16_t height() const {
    return GetField<uint16_t>(VT_HEIGHT, 0);
  }
  uint8_t levels_count() const {
    return GetField<uint8_t>(VT_LEVELS_COUNT, 1);
  }
  int32_t unk3() const {
    return GetField<int32_t>(VT_UNK3, 0);
  }
  sc::texture::SCTX::TextureFlags flags() const {
    return static_cast<sc::texture::SCTX::TextureFlags>(GetField<uint32_t>(VT_FLAGS, 0));
  }
  int32_t texture_length() const {
    return GetField<int32_t>(VT_TEXTURE_LENGTH, 0);
  }
  int32_t unk5() const {
    return GetField<int32_t>(VT_UNK5, 0);
  }
  int32_t unk6() const {
    return GetField<int32_t>(VT_UNK6, 0);
  }
  const sc::texture::SCTX::TextureVariants *variants() const {
    return GetPointer<const sc::texture::SCTX::TextureVariants *>(VT_VARIANTS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_UNK1, 4) &&
           VerifyField<uint32_t>(verifier, VT_PIXEL_TYPE, 4) &&
           VerifyField<uint16_t>(verifier, VT_WIDTH, 2) &&
           VerifyField<uint16_t>(verifier, VT_HEIGHT, 2) &&
           VerifyField<uint8_t>(verifier, VT_LEVELS_COUNT, 1) &&
           VerifyField<int32_t>(verifier, VT_UNK3, 4) &&
           VerifyField<uint32_t>(verifier, VT_FLAGS, 4) &&
           VerifyField<int32_t>(verifier, VT_TEXTURE_LENGTH, 4) &&
           VerifyField<int32_t>(verifier, VT_UNK5, 4) &&
           VerifyField<int32_t>(verifier, VT_UNK6, 4) &&
           VerifyOffset(verifier, VT_VARIANTS) &&
           verifier.VerifyTable(variants()) &&
           verifier.EndTable();
  }
};

struct TextureDataBuilder {
  typedef TextureData Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_unk1(int32_t unk1) {
    fbb_.AddElement<int32_t>(TextureData::VT_UNK1, unk1, 0);
  }
  void add_pixel_type(uint32_t pixel_type) {
    fbb_.AddElement<uint32_t>(TextureData::VT_PIXEL_TYPE, pixel_type, 0);
  }
  void add_width(uint16_t width) {
    fbb_.AddElement<uint16_t>(TextureData::VT_WIDTH, width, 0);
  }
  void add_height(uint16_t height) {
    fbb_.AddElement<uint16_t>(TextureData::VT_HEIGHT, height, 0);
  }
  void add_levels_count(uint8_t levels_count) {
    fbb_.AddElement<uint8_t>(TextureData::VT_LEVELS_COUNT, levels_count, 1);
  }
  void add_unk3(int32_t unk3) {
    fbb_.AddElement<int32_t>(TextureData::VT_UNK3, unk3, 0);
  }
  void add_flags(sc::texture::SCTX::TextureFlags flags) {
    fbb_.AddElement<uint32_t>(TextureData::VT_FLAGS, static_cast<uint32_t>(flags), 0);
  }
  void add_texture_length(int32_t texture_length) {
    fbb_.AddElement<int32_t>(TextureData::VT_TEXTURE_LENGTH, texture_length, 0);
  }
  void add_unk5(int32_t unk5) {
    fbb_.AddElement<int32_t>(TextureData::VT_UNK5, unk5, 0);
  }
  void add_unk6(int32_t unk6) {
    fbb_.AddElement<int32_t>(TextureData::VT_UNK6, unk6, 0);
  }
  void add_variants(::flatbuffers::Offset<sc::texture::SCTX::TextureVariants> variants) {
    fbb_.AddOffset(TextureData::VT_VARIANTS, variants);
  }
  explicit TextureDataBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TextureData> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TextureData>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TextureData> CreateTextureData(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    int32_t unk1 = 0,
    uint32_t pixel_type = 0,
    uint16_t width = 0,
    uint16_t height = 0,
    uint8_t levels_count = 1,
    int32_t unk3 = 0,
    sc::texture::SCTX::TextureFlags flags = static_cast<sc::texture::SCTX::TextureFlags>(0),
    int32_t texture_length = 0,
    int32_t unk5 = 0,
    int32_t unk6 = 0,
    ::flatbuffers::Offset<sc::texture::SCTX::TextureVariants> variants = 0) {
  TextureDataBuilder builder_(_fbb);
  builder_.add_variants(variants);
  builder_.add_unk6(unk6);
  builder_.add_unk5(unk5);
  builder_.add_texture_length(texture_length);
  builder_.add_flags(flags);
  builder_.add_unk3(unk3);
  builder_.add_pixel_type(pixel_type);
  builder_.add_unk1(unk1);
  builder_.add_height(height);
  builder_.add_width(width);
  builder_.add_levels_count(levels_count);
  return builder_.Finish();
}

inline const sc::texture::SCTX::TextureData *GetTextureData(const void *buf) {
  return ::flatbuffers::GetRoot<sc::texture::SCTX::TextureData>(buf);
}

inline const sc::texture::SCTX::TextureData *GetSizePrefixedTextureData(const void *buf) {
  return ::flatbuffers::GetSizePrefixedRoot<sc::texture::SCTX::TextureData>(buf);
}

inline const char *TextureDataIdentifier() {
  return "SCTX";
}

inline bool TextureDataBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, TextureDataIdentifier());
}

inline bool SizePrefixedTextureDataBufferHasIdentifier(const void *buf) {
  return ::flatbuffers::BufferHasIdentifier(
      buf, TextureDataIdentifier(), true);
}

inline bool VerifyTextureDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<sc::texture::SCTX::TextureData>(TextureDataIdentifier());
}

inline bool VerifySizePrefixedTextureDataBuffer(
    ::flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<sc::texture::SCTX::TextureData>(TextureDataIdentifier());
}

inline const char *TextureDataExtension() {
  return "sctx";
}

inline void FinishTextureDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sc::texture::SCTX::TextureData> root) {
  fbb.Finish(root, TextureDataIdentifier());
}

inline void FinishSizePrefixedTextureDataBuffer(
    ::flatbuffers::FlatBufferBuilder &fbb,
    ::flatbuffers::Offset<sc::texture::SCTX::TextureData> root) {
  fbb.FinishSizePrefixed(root, TextureDataIdentifier());
}

}  // namespace SCTX
}  // namespace texture
}  // namespace sc

#endif  // FLATBUFFERS_GENERATED_TEXTUREDATA_SC_TEXTURE_SCTX_H_
